[2025-07-12T00:00:24.880+0000] {processor.py:157} INFO - Started process (PID=6874) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:00:24.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:00:24.888+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:24.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:00:25.050+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:25.021+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:00:25.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:00:25.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.364 seconds
[2025-07-12T00:00:55.343+0000] {processor.py:157} INFO - Started process (PID=6885) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:00:55.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:00:55.345+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:55.345+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:00:55.368+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:00:55.364+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:00:55.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:00:55.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.081 seconds
[2025-07-12T00:01:25.733+0000] {processor.py:157} INFO - Started process (PID=6895) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:01:25.734+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:01:25.735+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:25.735+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:01:25.781+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:25.777+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:01:25.781+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:01:25.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.080 seconds
[2025-07-12T00:01:56.575+0000] {processor.py:157} INFO - Started process (PID=6905) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:01:56.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:01:56.578+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:56.578+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:01:56.592+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:01:56.589+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:01:56.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:01:56.643+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.071 seconds
[2025-07-12T00:02:27.922+0000] {processor.py:157} INFO - Started process (PID=6915) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:02:27.924+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:02:27.926+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:27.925+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:02:27.962+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:27.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:02:27.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:02:27.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.072 seconds
[2025-07-12T00:02:58.533+0000] {processor.py:157} INFO - Started process (PID=6925) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:02:58.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:02:58.536+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:58.535+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:02:58.553+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:02:58.550+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:02:58.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:02:58.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.068 seconds
[2025-07-12T00:03:28.961+0000] {processor.py:157} INFO - Started process (PID=6935) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:03:28.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:03:28.963+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:28.963+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:03:28.978+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:28.975+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:03:28.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:03:29.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.043 seconds
[2025-07-12T00:03:59.303+0000] {processor.py:157} INFO - Started process (PID=6945) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:03:59.305+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:03:59.307+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:59.306+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:03:59.323+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:03:59.321+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:03:59.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:03:59.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.051 seconds
[2025-07-12T00:04:29.724+0000] {processor.py:157} INFO - Started process (PID=6955) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:04:29.726+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:04:29.728+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:04:29.728+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:04:29.787+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:04:29.783+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:04:29.788+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:04:29.837+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.119 seconds
[2025-07-12T00:05:00.214+0000] {processor.py:157} INFO - Started process (PID=6965) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:05:00.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:05:00.216+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:05:00.216+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:05:00.228+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:05:00.225+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:05:00.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:05:00.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.055 seconds
[2025-07-12T00:06:20.069+0000] {processor.py:157} INFO - Started process (PID=6977) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:06:20.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:06:20.072+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:06:20.072+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:06:20.169+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:06:20.162+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:06:20.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:06:20.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.180 seconds
[2025-07-12T00:08:46.470+0000] {processor.py:157} INFO - Started process (PID=6987) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:08:46.472+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:08:46.483+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:08:46.475+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:08:46.906+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:08:46.890+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:08:46.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:08:47.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.670 seconds
[2025-07-12T00:09:17.375+0000] {processor.py:157} INFO - Started process (PID=6999) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:09:17.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:09:17.384+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:09:17.383+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:09:17.405+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:09:17.400+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:09:17.406+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:09:17.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.093 seconds
[2025-07-12T00:25:29.581+0000] {processor.py:157} INFO - Started process (PID=7011) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:25:29.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:25:29.584+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:25:29.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:25:29.609+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:25:29.604+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:25:29.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:25:29.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.089 seconds
[2025-07-12T00:31:12.373+0000] {processor.py:157} INFO - Started process (PID=7023) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:31:12.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:31:12.378+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:12.377+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:31:12.465+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:12.435+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:31:12.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:31:14.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 2.326 seconds
[2025-07-12T00:31:45.362+0000] {processor.py:157} INFO - Started process (PID=7033) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:31:45.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:31:45.369+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:45.368+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:31:45.428+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:31:45.415+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:31:45.429+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:31:45.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.203 seconds
[2025-07-12T00:32:15.969+0000] {processor.py:157} INFO - Started process (PID=7043) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:32:15.972+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:32:15.974+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:15.973+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:32:15.994+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:15.991+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:32:15.994+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:32:16.026+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.063 seconds
[2025-07-12T00:32:46.430+0000] {processor.py:157} INFO - Started process (PID=7053) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:32:46.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:32:46.441+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:46.439+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:32:46.493+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:32:46.486+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:32:46.494+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:32:46.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.129 seconds
[2025-07-12T00:33:17.094+0000] {processor.py:157} INFO - Started process (PID=7063) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:33:17.095+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:33:17.096+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:17.096+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:33:17.113+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:17.110+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:33:17.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:33:17.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.054 seconds
[2025-07-12T00:33:47.455+0000] {processor.py:157} INFO - Started process (PID=7073) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:33:47.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:33:47.456+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:47.456+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:33:47.474+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:33:47.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:33:47.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:33:47.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.051 seconds
[2025-07-12T00:34:17.926+0000] {processor.py:157} INFO - Started process (PID=7083) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:34:17.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:34:17.928+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:17.928+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:34:17.938+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:17.936+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:34:17.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:34:17.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.041 seconds
[2025-07-12T00:34:48.276+0000] {processor.py:157} INFO - Started process (PID=7093) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:34:48.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:34:48.278+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:48.278+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:34:48.294+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:34:48.291+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:34:48.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:34:48.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.059 seconds
[2025-07-12T00:35:18.641+0000] {processor.py:157} INFO - Started process (PID=7103) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:35:18.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:35:18.642+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:35:18.642+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:35:18.654+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:35:18.652+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:35:18.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:35:18.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.039 seconds
[2025-07-12T00:42:12.923+0000] {processor.py:157} INFO - Started process (PID=7115) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:42:13.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:42:13.430+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:13.429+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:42:14.026+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:13.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:42:14.036+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:42:14.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 2.187 seconds
[2025-07-12T00:42:45.202+0000] {processor.py:157} INFO - Started process (PID=7125) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:42:45.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:42:45.208+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:45.207+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:42:45.240+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:42:45.234+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:42:45.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:42:45.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.121 seconds
[2025-07-12T00:43:16.162+0000] {processor.py:157} INFO - Started process (PID=7135) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:43:16.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:43:16.167+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:16.166+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:43:16.226+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:16.210+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:43:16.229+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:43:16.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.216 seconds
[2025-07-12T00:43:46.885+0000] {processor.py:157} INFO - Started process (PID=7145) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:43:46.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:43:46.899+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:46.898+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:43:46.937+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:43:46.929+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:43:46.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:43:47.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.136 seconds
[2025-07-12T00:44:17.956+0000] {processor.py:157} INFO - Started process (PID=7155) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:44:17.957+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:44:17.959+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:17.958+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:44:17.976+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:17.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:44:17.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:44:18.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.061 seconds
[2025-07-12T00:44:48.842+0000] {processor.py:157} INFO - Started process (PID=7165) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:44:48.843+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:44:48.844+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:48.844+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:44:48.859+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:44:48.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:44:48.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:44:48.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.066 seconds
[2025-07-12T00:45:19.581+0000] {processor.py:157} INFO - Started process (PID=7175) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:45:19.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:45:19.586+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:19.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:45:19.626+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:19.620+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:45:19.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:45:19.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.124 seconds
[2025-07-12T00:45:50.258+0000] {processor.py:157} INFO - Started process (PID=7185) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:45:50.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:45:50.263+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:50.263+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:45:50.284+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:45:50.280+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:45:50.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:45:50.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.122 seconds
[2025-07-12T00:46:21.076+0000] {processor.py:157} INFO - Started process (PID=7195) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:46:21.078+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:46:21.080+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:21.079+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:46:21.103+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:21.100+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:46:21.103+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:46:21.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.091 seconds
[2025-07-12T00:46:51.600+0000] {processor.py:157} INFO - Started process (PID=7205) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:46:51.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:46:51.602+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:51.602+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:46:51.622+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:46:51.619+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:46:51.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:46:51.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.105 seconds
[2025-07-12T00:47:22.832+0000] {processor.py:157} INFO - Started process (PID=7215) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:47:22.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:47:22.846+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:22.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:47:22.890+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:22.870+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 5, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
ModuleNotFoundError: No module named 'src'
[2025-07-12T00:47:22.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:47:23.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.540 seconds
[2025-07-12T00:47:46.648+0000] {processor.py:157} INFO - Started process (PID=7222) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:47:46.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:47:46.660+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:46.659+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:47:47.841+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:47:47.796+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:47:47.886+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:47:48.172+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 1.541 seconds
[2025-07-12T00:48:18.535+0000] {processor.py:157} INFO - Started process (PID=7232) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:48:18.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:48:18.538+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:18.538+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:48:18.593+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:18.588+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:48:18.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:48:18.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.111 seconds
[2025-07-12T00:48:48.863+0000] {processor.py:157} INFO - Started process (PID=7242) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:48:48.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:48:48.879+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:48.872+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:48:48.988+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:48:48.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:48:48.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:48:49.071+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.219 seconds
[2025-07-12T00:49:19.960+0000] {processor.py:157} INFO - Started process (PID=7252) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:49:19.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:49:19.963+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:19.963+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:49:20.006+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:20.001+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:49:20.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:49:20.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.117 seconds
[2025-07-12T00:49:51.320+0000] {processor.py:157} INFO - Started process (PID=7262) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:49:51.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:49:51.328+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:51.327+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:49:51.532+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:49:51.504+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:49:51.541+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:49:51.854+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.558 seconds
[2025-07-12T00:50:22.277+0000] {processor.py:157} INFO - Started process (PID=7272) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:50:22.283+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:50:22.291+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:22.289+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:50:22.367+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:22.354+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:50:22.368+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:50:22.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.180 seconds
[2025-07-12T00:50:53.094+0000] {processor.py:157} INFO - Started process (PID=7284) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:50:53.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:50:53.100+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:53.099+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:50:53.153+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:50:53.143+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:50:53.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:50:53.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.117 seconds
[2025-07-12T00:51:23.975+0000] {processor.py:157} INFO - Started process (PID=7295) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:51:23.980+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:51:23.982+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:23.981+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:51:24.048+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:24.035+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:51:24.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:51:24.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.154 seconds
[2025-07-12T00:51:54.361+0000] {processor.py:157} INFO - Started process (PID=7305) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:51:54.364+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:51:54.366+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:54.365+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:51:54.396+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:51:54.392+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:51:54.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:51:54.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.074 seconds
[2025-07-12T00:52:25.141+0000] {processor.py:157} INFO - Started process (PID=7315) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:52:25.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:52:25.149+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:25.148+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:52:25.227+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:25.216+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:52:25.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:52:25.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.172 seconds
[2025-07-12T00:52:55.578+0000] {processor.py:157} INFO - Started process (PID=7325) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:52:55.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:52:55.580+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:55.580+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:52:55.634+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:52:55.627+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:52:55.635+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:52:55.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.114 seconds
[2025-07-12T00:53:26.009+0000] {processor.py:157} INFO - Started process (PID=7335) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:53:26.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:53:26.014+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:26.014+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:53:26.090+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:26.081+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:53:26.091+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:53:26.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.147 seconds
[2025-07-12T00:53:57.125+0000] {processor.py:157} INFO - Started process (PID=7345) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:53:57.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:53:57.133+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:57.132+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:53:57.194+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:53:57.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:53:57.196+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:53:57.252+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.135 seconds
[2025-07-12T00:54:27.836+0000] {processor.py:157} INFO - Started process (PID=7355) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:54:27.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:54:27.843+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:27.842+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:54:27.913+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:27.906+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:54:27.914+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:54:27.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.166 seconds
[2025-07-12T00:54:58.375+0000] {processor.py:157} INFO - Started process (PID=7365) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:54:58.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:54:58.378+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:58.378+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:54:58.427+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:54:58.419+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:54:58.428+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:54:58.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.106 seconds
[2025-07-12T00:55:28.828+0000] {processor.py:157} INFO - Started process (PID=7375) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:55:28.832+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:55:28.835+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:28.834+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:55:28.923+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:28.910+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:55:28.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:55:28.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.159 seconds
[2025-07-12T00:55:59.545+0000] {processor.py:157} INFO - Started process (PID=7385) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:55:59.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:55:59.547+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:59.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:55:59.578+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:55:59.574+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:55:59.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:55:59.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.064 seconds
[2025-07-12T00:56:30.326+0000] {processor.py:157} INFO - Started process (PID=7395) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:56:30.327+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:56:30.330+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:56:30.329+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:56:30.458+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:56:30.449+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:56:30.459+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:56:30.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.210 seconds
[2025-07-12T00:57:00.892+0000] {processor.py:157} INFO - Started process (PID=7405) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:57:00.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:57:00.897+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:00.896+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:57:00.968+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:00.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:57:00.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:57:01.049+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.167 seconds
[2025-07-12T00:57:32.021+0000] {processor.py:157} INFO - Started process (PID=7415) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:57:32.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:57:32.024+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:32.023+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:57:32.076+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:57:32.068+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:57:32.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:57:32.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.109 seconds
[2025-07-12T00:58:02.284+0000] {processor.py:157} INFO - Started process (PID=7425) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:58:02.285+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:58:02.286+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:02.286+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:58:02.318+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:02.314+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:58:02.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:58:02.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.089 seconds
[2025-07-12T00:58:32.977+0000] {processor.py:157} INFO - Started process (PID=7435) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:58:32.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:58:32.981+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:32.980+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:58:33.015+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:58:33.011+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:58:33.015+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:58:33.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.088 seconds
[2025-07-12T00:59:03.889+0000] {processor.py:157} INFO - Started process (PID=7445) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:59:03.892+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:59:03.893+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:03.893+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:59:03.944+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:03.935+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:59:03.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:59:04.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.161 seconds
[2025-07-12T00:59:34.738+0000] {processor.py:157} INFO - Started process (PID=7455) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:59:34.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T00:59:34.740+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:34.740+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:59:34.799+0000] {logging_mixin.py:151} INFO - [2025-07-12T00:59:34.793+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T00:59:34.800+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T00:59:34.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.130 seconds
[2025-07-12T01:00:06.099+0000] {processor.py:157} INFO - Started process (PID=7464) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:00:06.114+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T01:00:06.121+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:06.116+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:00:06.242+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:06.234+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T01:00:06.243+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:00:06.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.248 seconds
[2025-07-12T01:00:37.775+0000] {processor.py:157} INFO - Started process (PID=7475) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:00:37.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T01:00:37.781+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:37.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:00:37.930+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:00:37.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T01:00:37.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:00:38.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.283 seconds
[2025-07-12T01:01:09.001+0000] {processor.py:157} INFO - Started process (PID=7485) to work on /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:01:09.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/nlp_data_pipeline.py for tasks to queue
[2025-07-12T01:01:09.005+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:01:09.004+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:01:09.058+0000] {logging_mixin.py:151} INFO - [2025-07-12T01:01:09.041+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/nlp_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/nlp_data_pipeline.py", line 11, in <module>
    from src.data.data_loader import download_dataset, prepare_dataset
  File "/opt/airflow/src/data/data_loader.py", line 2, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'
[2025-07-12T01:01:09.060+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/nlp_data_pipeline.py
[2025-07-12T01:01:09.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/nlp_data_pipeline.py took 0.144 seconds
